apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-maven-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-maven-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50